#!/usr/bin/env python2.7

# working species in Ensembl Variants, as of November 2014
# based on ftp://ftp.ensembl.org/pub/release-77/variation/vcf/
ensembl_species = ["bos_taurus",
                   "canis_familiaris",
                   "danio_rerio",
                   "drosophila_melanogaster",
                   "equus_caballus",
                   "felis_catus",
                   "gallus_gallus",
                   "homo_sapiens",
                   "macaca_mulatta",
                   "meleagris_gallopavo",
                   "monodelphis_domestica",
                   "mus_musculus",
                   "nomascus_leucogenys",
                   "ornithorhynchus_anatinus",
                   "ovis_aries",
                   "pan_troglodytes",
                   "pongo_abelii",
                   "rattus_norvegicus",
                   "saccharomyces_cerevisiae",
                   "sus_scrofa",
                   "taeniopygia_guttata",
                   "tetraodon_nigroviridis"]

# simple dictionaries used to convert 1-len to 3-len residues
aa_symbols_rev_ext = {'A': 'ALA', 'C': 'CYS', 'D': 'ASP',
                      'E': 'GLU', 'F': 'PHE', 'G': 'GLY',
                      'H': 'HIS', 'K': 'LYS', 'I': 'ILE',
                      'L': 'LEU', 'M': 'MET', 'N': 'ASN',
                      'P': 'PRO', 'Q': 'GLN', 'R': 'ARG',
                      'S': 'SER', 'T': 'THR', 'V': 'VAL',
                      'Y': 'TYR', 'W': 'TRP',
                      'X': 'XXX', '-': '---', '*': '***',
                      'B': 'ASX', 'Z': 'GLX', 'J': 'XLE',
                      'U': 'SEC', 'O': 'PYL'}

# simple dictionaries used to convert 3-len to 1-len residues
aa_symbols_ext = {'ALA': 'A', 'CYS': 'C', 'ASP': 'D',
                  'GLU': 'E', 'PHE': 'F', 'GLY': 'G',
                  'HIS': 'H', 'LYS': 'K', 'ILE': 'I',
                  'LEU': 'L', 'MET': 'M', 'ASN': 'N',
                  'PRO': 'P', 'GLN': 'Q', 'ARG': 'R',
                  'SER': 'S', 'THR': 'T', 'VAL': 'V',
                  'TYR': 'Y', 'TRP': 'W',
                  # other
                  'XXX': 'X', '---': '-', '***': '*',
                  'ASX': 'B', 'GLX': 'Z', 'XLE': 'J',
                  'SEC': 'U', 'PYL': 'O', 'CSO': 'C',
                  'HIP': 'H', 'HSD': 'X', 'HSE': 'S',
                  'HSP': 'X', 'MSE': 'M', 'SEP': 'S',
                  'TPO': 'T', 'PTR': 'Y', 'XAA': 'X',
                  'AIB': 'A', 'PHL': 'F', 'CSS': 'C',
                  'ALM': 'X', 'MPR': 'X', 'FRD': 'X',
                  'LYM': 'X', 'GLM': 'X', 'PPH': 'X',
                  'PGL': 'X', 'OLE': 'X', 'ABA': 'A',
                  'NLE': 'L', 'B2V': 'V', 'B2I': 'I',
                  'B1F': 'X', 'BNO': 'X', 'B2A': 'A',
                  'B2F': 'F', 'IVA': 'X', 'LOV': 'X',
                  'STA': 'X', 'PVL': 'X', 'CAL': 'X',
                  'PHA': 'F', 'DCI': 'X', 'AHS': 'X',
                  'CHS': 'X', 'ETA': 'X', 'PCA': 'E',
                  'UNK': 'X', 'CYH': 'X', '-': '-'}

# Protein sequence alignments: a strategy for the hierarchical
# analysis of residue conservation. Livingstone & Barton (1993).
aa_physicochemical_full = {'ALA': ['hydrophobic', 'small', 'tiny'],
                           'CYS': ['hydrophobic', 'small'],
                           'GLU': ['polar', 'negative', 'charged'],
                           'ASP': ['polar', 'small', 'negative', 'charged'],
                           'GLY': ['hydrophobic', 'small', 'tiny'],
                           'PHE': ['hydrophobic', 'aromatic'],
                           'ILE': ['hydrophobic', 'aliphatic'],
                           'HIS': ['hydrophobic', 'polar', 'aromatic', 'positive', 'charged'],
                           'LYS': ['hydrophobic', 'polar', 'aromatic', 'positive', 'charged'],
                           'MET': ['hydrophobic'],
                           'LEU': ['hydrophobic', 'aliphatic'],
                           'ASN': ['polar', 'small'],
                           'GLN': ['polar'],
                           'PRO': ['small', 'proline'],
                           'SER': ['polar', 'small', 'tiny'],
                           'ARG': ['polar', 'positive', 'charged'],
                           'THR': ['hydrophobic', 'polar', 'small'],
                           'TRP': ['hydrophobic', 'polar', 'aromatic'],
                           'VAL': ['hydrophobic', 'small', 'aliphatic'],
                           'TYR': ['hydrophobic', 'polar'],
                           '---': ['stop'], '-': ['stop'],
                           '***': ['stop'], '*': ['stop'],
                           'XXX': ['stop'], 'X': ['stop']}
